version: '2'

networks:
  default:
    driver: overlay

services:
  nifinode:
    volumes:
      - /etc/security/swarm/nifi/certs:/etc/security/certs:ro
      - /etc/security/swarm/nifi/keytabs:/etc/security/keytabs:ro
      - /HDPCONFIGPATH:/mnt/nifi:ro
      - /mnt/swarm/nifi/scripts:/scripts:ro
    ports:
      - 8080:8080
    environment:
      NIFI_UI_BANNER_TEXT: 'Banner Text'
      NIFI_JAVA_MINHEAP: '-Xms4g'
      NIFI_JAVA_MAXHEAP: '-Xmx8g'
      KRB_REALM: 'REALM.EXAMPLE.COM'
      NIFI_KEY_PASS: pass
      NIFI_ADMIN: admin@REALM.EXAMPLE.COM
      NIFI_ZOOKEEPER: 'ZKINSTANCELIST'
      #constraint:node: '=NODEFQDN'
